use mazecraze::core::Point;
use mazecraze::generator::{all_generators, MazeGenerator};
use mazecraze::solver::all_solvers;

/// Integration test: every generator + solver combination should produce a valid solution.
#[test]
fn test_all_generator_solver_combinations() {
    let generators = all_generators();
    let solvers = all_solvers();
    let start = Point::new(1, 1);
    let end = Point::new(13, 13);

    for gen in &generators {
        let gen_recorder = gen.generate(15, 15);
        let grid = gen_recorder.frames().last().unwrap().grid.clone();

        for solver in &solvers {
            let solve_recorder = solver.solve(&grid, start, end);
            let final_frame = solve_recorder.frames().last().unwrap();

            // Scan entire grid for Path cells (passages() only returns Cell::Passage)
            let has_path = (0..final_frame.grid.height()).any(|y| {
                (0..final_frame.grid.width()).any(|x| {
                    matches!(
                        final_frame.grid.get(Point::new(x, y)),
                        Some(mazecraze::core::Cell::Path)
                    )
                })
            });

            assert!(
                has_path,
                "{} failed to solve maze generated by {}",
                solver.name(),
                gen.name()
            );
        }
    }
}

/// Integration test: export functionality.
#[test]
fn test_export_to_text() {
    use mazecraze::export::export_to_text;
    use mazecraze::generator::RecursiveBacktracker;

    let gen = RecursiveBacktracker::new();
    let recorder = gen.generate(11, 11);
    let grid = recorder.frames().last().unwrap().grid.clone();

    let temp_path = std::env::temp_dir().join("mazecraze_test_export.txt");
    export_to_text(&grid, &temp_path).expect("export should succeed");

    let content = std::fs::read_to_string(&temp_path).expect("should read back");
    assert!(!content.is_empty(), "exported file should not be empty");
    assert!(
        content.contains('│') || content.contains('|'),
        "should contain wall characters"
    );

    std::fs::remove_file(&temp_path).ok();
}
